### PR TITLE
Improve README, add CI

### PR DESCRIPTION
**Pull request by davetcoleman**
Add CI

### CODE REVIEW

**Comment by davetcoleman** [comment]
@mikeferguson or @v4hn can you take a look at the new repo and this PR?

@ugocupcic do you mind updating the documentation and Docker build to point to here instead?

**Comment by ugocupcic** [comment]
@davetcoleman Done. Hopefully I didn't miss any links. Cheers

**Comment by v4hn** [comment]
@davetcoleman I'm not really involved with the travis setups.
If you tell me it works as it should then I can merge it though.

**Comment by davetcoleman** [comment]
@v4hn you needn't review the travis part, just the overall repo move that you had requested @mikeferguson do in another thread. thanks!

**Comment by davetcoleman** [comment]
ping

**Comment by v4hn** [comment]
Sorry for the late response.
I don't use the warehouse myself up to now, so I cannot test this properly.
I assume @ugocupcic did so as he contributed to support mongo again.
I'll add this repo to my moveit workspace and compile it later today, if I find anything weird I'll add pull-requests. But I cannot make sure this actually works.

Looks like travis already found an install issue with the repo, or is this travis specific again?

**Comment by v4hn** [comment]
@davetcoleman See #4 for my "review" :)

**Comment by davetcoleman** [comment]
@v4hn lets merge this first - this PR is very simple.

**Pull request merged**
