### PR TITLE
[ROS2] Add prerelease tests

### PR DESCRIPTION
**Pull request by vatanaksoytezer**

### CODE REVIEW

**Comment by vatanaksoytezer** [comment]
Rolling and Galactic is failing because of SSL @tylerjw @henningkayser

**Comment by vatanaksoytezer** [comment]
@henningkayser can you re-trigger this with the last fix

**Comment by henningkayser** [comment]
> @henningkayser can you re-trigger this with the last fix

Shouldn't you update this branch first?

**Comment by vatanaksoytezer** [comment]
> Shouldn't you update this branch first?

Sure, rebasing now

**Comment by vatanaksoytezer** [comment]
This is now failing as `warehouse_ros` is not released in Galactic

**Comment by vatanaksoytezer** [comment]
SSL issue also seems to persist on Rolling.

**Comment by henningkayser** [comment]
> SSL issue also seems to persist on Rolling.

#63 fixed rolling

**Review by henningkayser — APPROVED** [review]

**Pull request merged**
