### PR TITLE
[WIP] Enable unit test

### LINKED ISSUE #7: Tests broken
When building this package's tests this error occurs: https://gist.github.com/davetcoleman/f5dddabaa85c373f61cd2a906170a956

### PR DESCRIPTION
**Pull request by rhaschke**
This is an attempt to fix #7. Building on #25, 532879a re-enables the unit tests, manually starting mongodb-server.
The tests can connect to the database now. However, I get the following failure now:
```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from MongoRos
[ RUN      ] MongoRos.MongoRos
/root/ws_moveit/src/mongo/test/test_warehouse_ros_mongo.cpp:104: Failure
      Expected: 1u
      Which is: 1
To be equal to: res.size()
      Which is: 0
Segmentation fault (core dumped)
```
I can see, that the database is correctly filled with values:
```
> db.poses.find()
{ "_id" : ObjectId("5d547bd127f870d8c71e633c"), "x" : 24, "y" : 42, "name" : "bar", "creation_time" : 1565817809.5413783, "blob_id" : ObjectId("5d547bd127f870d8c71e633d") }
{ "_id" : ObjectId("5d547bd127f870d8c71e633f"), "x" : 10, "y" : 532, "name" : "baz", "creation_time" : 1565817809.544326, "blob_id" : ObjectId("5d547bd127f870d8c71e6340") }
{ "_id" : ObjectId("5d547bd127f870d8c71e6342"), "x" : 53, "y" : 22, "name" : "qux", "creation_time" : 1565817809.544997, "blob_id" : ObjectId("5d547bd127f870d8c71e6343") }
{ "_id" : ObjectId("5d547bd127f870d8c71e6345"), "x" : 24, "y" : 42, "name" : "oof", "creation_time" : 1565817809.5455735, "blob_id" : ObjectId("5d547bd127f870d8c71e6346") }
{ "_id" : ObjectId("5d547bd127f870d8c71e6348"), "x" : 22, "y" : -5, "name" : "ooof", "creation_time" : 1565817809.546149, "blob_id" : ObjectId("5d547bd127f870d8c71e6349") }
```
But, I have no idea, why accessing those values doesn't work.
@christian-rauch, could you have a look please?

### CODE REVIEW

**Comment by christian-rauch** [comment]
I can reproduce this locally with `rosrun warehouse_ros_mongo test_warehouse_ros_mongo_cpp`.

**Comment by christian-rauch** [comment]
Thanks to the very useful ROS plugin for Qt Creator (and the ClangCodeModel), I saw that the query construction uses the "wrong" `append` method: `warning: implicit conversion turns string literal into bool: 'const char [7]' to 'bool'`.

I have no explanation of why the compiler resolves this to the wrong signature. Might this because the string-valued function uses a const reference?

Fixed in https://github.com/rhaschke/warehouse_ros_mongo/pull/1

**Comment by christian-rauch** [comment]
I cannot run the python tests `rosrun warehouse_ros_mongo test_warehouse_ros_mongo_py.py` because module `warehouse_ros` is missing.
Where is this module? I do not see any python references in https://github.com/ros-planning/warehouse_ros.

**Comment by rhaschke** [comment]
The python module was removed in https://github.com/ros-planning/warehouse_ros/pull/32.
I removed it here now as well.

**Comment by rhaschke** [comment]
I had some trouble with getting the unit tests running again. Finally, the core issue seems to be a bug in gcc: if optimization level >= 2 is enabled, some mongo symbols are not correctly exported anymore.

**Comment by rhaschke** [comment]
Merged without temporary Travis fix (to build `warehouse_ros` from source).

**Pull request closed without merging**
