### PR TITLE
Migrate from Travis to GitHub Actions [ros2]

### PR DESCRIPTION
**Pull request by tylerjw**
Same as I did here: https://github.com/ros-planning/geometric_shapes/pull/169

This is mostly copy-pasta and will rescue this repo out of the infinite queue of Travis.

Here is my fork where this action will run until I get this merged here: https://github.com/tylerjw/warehouse_ros_mongo/pull/1

### CODE REVIEW

**Comment by tylerjw** [comment]
I'm going to add an issue to enable clang-tidy.  It wasn't enabled in the travis config and I discovered enabling it produces a ton of warnings I don't have time to fix as part of this.

**Comment by tylerjw** [comment]
The test is failing on `main` repo but passing on `testing` ros repo.  This makes no sense to me as how it is failing has something to do with the mongodb process it starts just fails to start.  :cry:

**Comment by tylerjw** [comment]
It is passing on one of the two testing runs.  I'm not sure what to think.  Using the `rerun_ci` I've tried reproducing the failure locally but have been unable to.  I think this means we have a flaky test and I'm going to just leave this here until I know why or someone else fixes it.

**Comment by tylerjw** [comment]
To test this locally [use the instructions here](https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#simplest-way-to-run-locally).  Then run this command:

```bash
rosrun industrial_ci rerun_ci . ROS_DISTRO=foxy ROS_REPO=main CCACHE_DIR="$HOME/.ccache"
```

**Comment by tylerjw** [comment]
I don't understand why this was failing yesterday.  I've ran in multiple times today on GitHub Actions and it passes every time.  It is also passing locally for me.  I think this is ready for review.

**Review by rhaschke — APPROVED** [review]

**Comment by tylerjw** [comment]
I didn't update the readme :facepalm:

**Pull request merged**
