### PR TITLE
Add Galactic CI

### PR DESCRIPTION
**Pull request by vatanaksoytezer**

### CODE REVIEW

**Review by henningkayser — APPROVED** [review]
Just in general: do we really need main and testing for all distros or should we more rely on Rolling to act as testing target?

**Comment by vatanaksoytezer** [comment]
> Just in general: do we really need main and testing for all distros or should we more rely on Rolling to act as testing target?

I think it is a good practice to test on both main and testing, rather than relying on rolling only. Because foxy-testing and rolling are quite different tests. Maybe @tylerjw can chime in with his opinions to this as well.

**Comment by tylerjw** [comment]
I think we should test both galactic and rolling because even if they are very similar now they will eventually differ as rolling continues to change.

**Comment by henningkayser** [comment]
> I think we should test both galactic and rolling because even if they are very similar now they will eventually differ as rolling continues to change.

I agree that we should test all distros. I was just wondering if testing really needs to be enabled for all.

**Pull request merged**
