### PR TITLE
Fix compilation errors

### PR DESCRIPTION
**Pull request by vmatare**
Mostly due to missing `libstc++` includes & changes in `mongo-cxx-driver-1.0.0`

### CODE REVIEW

**Comment by vmatare** [comment]
Sorry, had to amend a few times but it seems pull requests are merged recursively. I'll let this sit until the Travis build completes, but then I'll make a new pull request without the bogus merges.

**Comment by vmatare** [comment]
Okay, seems like the pull request was automatically rebased, only now the Travis build fails due to some other error :-/

**Comment by v4hn** [comment]
Sorry, I nearly missed this request. For some reason I wasn't watching the repo.

The only error message I can find in here is
```
wstool rm warehouse_ros_mongo
ERROR in config: Unknown elements '['warehouse_ros_mongo']'
```
and this is probably not related to your change.
@davetcoleman Oh wise master of the CI, what is this error about? :)

**Review by v4hn — APPROVED** [review]
I just verified that this compiles with both the 26compat version of mongo-cxx-driver (the one we currently advertise to use) as well as their "legacy" branch (despite the name this is the successor of 26compat and the basis of 1.1.x releases).

Thank you for the contribution @vmatare !

**Comment by davetcoleman** [comment]
The error is not because of ``wstool rm warehouse_ros_mongo`` - that line of the moveit_ci [cannot kill the docker](https://github.com/ros-planning/moveit_ci/blob/master/travis.sh#L119). The error can be safely ignored and only indicates that the default [build](https://raw.githubusercontent.com/ros-planning/moveit/kinetic-devel/moveit.rosinstall) of moveit does not include ``warehouse_ros_mongo``.

The issue is either the Travis output log is too long and therefore terminates the process, or the Travis timeout was triggered. 42 minutes should not trigger the timeout, so it must be the log output. We are building ``mongo-cxx-driver`` from source [here](https://github.com/ros-planning/warehouse_ros_mongo/blob/jade-devel/.travis.before_script) and it has a lot of output in Travis, so I think that is the problem. I will propose a fix in a separate PR.

**Comment by davetcoleman** [comment]
I have (re)found the problem - this package's tests have been [broken for a while](https://github.com/ros-planning/warehouse_ros_mongo/issues/7). @vmatare think you could look into that by running locally:

```
catkin build --no-status --summarize --make-args tests -- --no-deps warehouse_ros_mongo
```

? Thanks!

**Comment by v4hn** [comment]
@davetcoleman This request improves the current state of the module as is.
I would like to see this merged for now. Let's discuss & track the broken tests separately in #7.

**Review by davetcoleman — APPROVED** [review]

**Pull request merged**
