### PR TITLE
Add codecov reporting and black formatting

### PR DESCRIPTION
**Pull request by tylerjw**
This also fixes the ccache dir issue and saves test failure files.

### CODE REVIEW

**Comment by rhaschke** [comment]
Looks like this is failing now: https://github.com/ros-planning/warehouse_ros_mongo/actions/runs/676829394

**Comment by tylerjw** [comment]
> Looks like this is failing now: https://github.com/ros-planning/warehouse_ros_mongo/actions/runs/676829394

I've been trying to debug it and I can't figure it out.  This test seems to fail occasionally because mongo itself won't start.  I think this is the same failure I was seeing earlier that seemed to disappear.  I've not been able to reproduce this locally.

**Comment by rhaschke** [comment]
Hm. Looks like the test is flaky. Now the referenced link shows a successful build.
Maybe, mongo is too slow to startup and thus not ready yet if the test app tries to connect?

**Comment by tylerjw** [comment]
> Maybe, mongo is too slow to startup and thus not ready yet if the test app tries to connect?

That's my suspicion but I tried increasing the time and couldn't get that to make a difference.  Also, it only happens on foxy runners.

**Comment by rhaschke** [comment]
Don't worry too much for now...

**Pull request merged**
