### PR TITLE
use stock libmongoclient-dev on Melodic

### PR DESCRIPTION
**Pull request by rhaschke**
Addresses #14

### CODE REVIEW

**Comment by christian-rauch** [comment]
Unfortunately, `libmongoclient-dev` is only available on Ubuntu 18.04. The osdep in rosdistro does not differentiate between Ubuntu versions and a call to rosdep will fail for Ubuntu 16.04.

Edit: I see, this is a `melodic` only branch.

**Comment by rhaschke** [comment]
> Unfortunately, libmongoclient-dev is only available on Ubuntu 18.04.

I know. That's why this PR will open a new branch melodic-devel. Last commit removes jade + kinetic from Travis CI. Did I missed something else?

**Comment by christian-rauch** [comment]
This works. Compiles and connects to the database.

**Comment by rhaschke** [comment]
Great. Going to merge.

**Comment by rhaschke** [comment]
Merged as melodic-devel branch.

**Pull request closed without merging**
